all:
 children:
  master:
   hosts:
    master1:
     ansible_host: 127.1
  worker:
   hosts:
    worker1:
     ansible_host: 192.168.1.31
    worker2:
     ansible_host: 192.168.1.32
    worker3:
     ansible_host: 192.168.1.33
 vars:
  ansible_user: root
  ansible_password: Passw0rd!
