---
- hosts: all
  tasks:
  - name: "kubeadm reset"
    become: yes
    shell: echo y|kubeadm reset
- hosts: master
  tasks:
  - name: "cleanUp"
    shell: rm -rf /home/administrator/.kube
  - name: "init"
    become: yes
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 | tee init.log
  - name: "config allowance for administrator to use k8s"
    become: true
    shell: mkdir -p $HOME/.kube && sudo cp /etc/kubernetes/admin.conf $HOME/.kube/config && sudo chown $(id -u):$(id -g) $HOME/.kube/config
